<?php

/**
 * Implements hook_permission();
 */
function adef_camps_permission() {
  $perms['register participants'] = array(
      'title' => t('Register Participants'),
      'description' => t('Register particioants into sessions and modifies their registration')
  );
  $perms['session attendance'] = array(
      'title' => t('Override Attendance Edit'),
      'description' => t('Edit session attendance even if not registsred as session trainer.')
  );
  $perms['administer settings'] = array(
      'title' => t('Administer Camps Settings'),
      'description' => t('Administer general camps settings like dates.')
  );
  $perms['add incidents'] = array(
      'title' => t('Add Incidents'),
      'description' => t('Add incidents to participants.')
  );
  $perms['add achievements'] = array(
      'title' => t('Add Achievments'),
      'description' => t('Add achievements to particpants.')
  );
  $perms['bulk generate spacetime'] = array(
      'title' => t('Bulk Create space-time'),
      'descriptiojn' => t('Has access to admin tool to create bulk space-time slots (zamakan)'),
  );
  return $perms;
}

/**
 * Implements hook_menu();
 */
function adef_camps_menu() {
  $items = array();
  $items['node/%node/registeration'] = array(
      'title' => 'Registration',
      'page callback' => 'adef_camps_register',
      'page arguments' => array(1),
      'access arguments' => array(1),
      'access callback' => 'adef_camps_participant_access',
      'type' => MENU_LOCAL_TASK,
      'file' => 'adef_camps.pages.inc',
      'weight' => 100,
  );
  $items['node/%node/incident'] = array(
      'title' => 'Incidents',
      'page callback' => 'adef_camps_registry',
      'page arguments' => array(1, 2),
      'access arguments' => array(1),
      'access callback' => 'adef_camps_participant_access',
      'type' => MENU_LOCAL_TASK,
      'file' => 'adef_camps.pages.inc',
      'weight' => 101,
  );
  $items['node/%node/achievement'] = array(
      'title' => 'Achievments',
      'page callback' => 'adef_camps_registry',
      'page arguments' => array(1, 2),
      'access arguments' => array(1),
      'access callback' => 'adef_camps_participant_access',
      'type' => MENU_LOCAL_TASK,
      'file' => 'adef_camps.pages.inc',
      'weight' => 102,
  );
  $items['node/%node/schedule'] = array(
      'title' => 'Schedule',
      'page callback' => 'adef_camps_schedule',
      'page arguments' => array(1),
      'access arguments' => array(1),
      'access callback' => 'adef_camps_participant_access',
      'type' => MENU_LOCAL_TASK,
      'file' => 'adef_camps.pages.inc',
      'weight' => 98,
  );
  $items['adefcamps/registration/slots'] = array(
      'type' => MENU_CALLBACK,
      'access arguments' => array('register participants'),
      'page callback' => 'adef_camps_registration_slots',
      'file' => 'adef_camps.api.inc'
  );
//  $items['node/%node/attendance'] = array(
//      'title' => 'Attendance',
//      'page callback' => 'adef_camps_attendance',
//      'page arguments' => array(1),
//      'access arguments' => array(1),
//      'access callback' => 'adef_camps_attendance_access',
//      'type' => MENU_LOCAL_TASK,
//      'file' => 'adef_camps.pages.inc',
//      'weight' => 100,
//  );
  $items['admin/config/system/adefcamps'] = array(
      'title' => 'ADEF Camps',
      'page callback' => 'adef_camps_configure',
      'access arguments' => array('administer settings'),
      'file' => 'adef_camps_admin.inc',
  );

  $items['admin/config/system/adefcamps/settings'] = array(
      'title' => 'Settings',
      'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/system/adefcamps/generateslots'] = array(
      'title' => 'Generate Space-time Slots',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'adef_camps_generate_slots',
      'access arguments' => array('bulk generate spacetime'),
      'file' => 'adef_camps_admin.inc',
  );

  return $items;
}

/**
 * Implements hook_views_pre_render
 */
function adef_camps_views_pre_render(&$view) {
  switch ($view->name . "-" . $view->current_display) {
    case 'content_blocks-page_schedule':
      drupal_add_js(drupal_get_path('module', 'adef_camps') . '/js/adef_camps_ui_common.js');
      drupal_add_js(drupal_get_path('module', 'adef_camps') . '/js/adef_camps_schedule.js');
      break;
    default:
      break;
  }
}

/**
 * Implementation of hook_views_api().
 */
function adef_camps_views_api() {
  return array(
    'api' => 3,
    'template path' => drupal_get_path('module', 'adef_camps') . '/templates',
  );
}

/**
 * Access callback for particpants incidents and registration
 * @param type $node
 * @return boolean
 */
function adef_camps_participant_access($node) {
  if ($node->type == 'participant' && (user_access('register participants') || user_access('add incidents') || user_access('add achievements'))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Access callback function for attendance
 * @global type $user
 * @param type $node
 * @return boolean
 */
function adef_camps_attendance_access($node) {
  if ($node->type == 'timespace') {
    if (user_access('session attendance')) {
      return TRUE;
    }
    global $user;
    $trainers = views_get_view_result('content_blocks', 'block_trainers', $node->nid);
    foreach ($trainers[0]->field_field_trainers as $trainer) {
      if ($trainer['raw']['target_id'] == $user->uid) {
        return TRUE;
      }
    }
  }
  return FALSE;
}

/**
 * Implements hook_node_update();
 * @todo test again but disable for now
 */
function adef_camps_node_update($node) {
  switch ($node->type) {
    case 'workshop':
      break; //disabled
      $query = new EntityFieldQuery();
      $query->entityCondition('entity_type', 'node')
              ->entityCondition('bundle', 'session')
              ->fieldCondition('field_workshop', 'target_id', $node->nid, '=');
      $result = $query->execute();
      $nodes = array_keys($result['node']);
      auto_nodetitle_operations_update($nodes);
      break;

    default:
      break;
  }
}

/**
 * Implements hook_node_insert();
 */
function adef_camps_node_insert($node) {
  switch ($node->type) {
    case 'workshop':
      adef_camps_create_session_for_workshop($node);
      break;

    default:
      break;
  }
}

/**
 * Implements hook_rules_action_info();
 */
function adef_camps_rules_action_info() {
  $items = array(
      'adef_camps_action_updatesessions' => array(
          'label' => t('Update title of related sessions.'),
          'group' => t('ADEF Camps'),
          'parameter' => array(
              'nid' => array(
                  'type' => 'integer',
                  'label' => t('Node ID'),
                  'description' => t('Node'),
                  'restriction' => 'selector',
                  'wrapped' => FALSE,
                  'allow null' => FALSE,
              ),
          ),
      ),
  );
  return $items;
}

function adef_camps_action_updatesessions($nid) {
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'session')
          ->fieldCondition('field_workshop', 'target_id', $nid, '=');
  $result = $query->execute();
  $nodes = array_keys($result['node']);
  auto_nodetitle_operations_update($nodes);
}

function adef_camps_session_serial($node) {
  
}

/**
 * Implements hook_action_info();
 */
function adef_camps_action_info() {
  $actions['adef_camps_create_session_for_workshop'] = array(
      'type' => 'node',
      'label' => t('Create related sessions.'),
      'configurable' => FALSE,
  );
  return $actions;
}

function adef_camps_create_session_for_workshop($workshop_node) {
  global $user;
  $langcode = language_default('language');

  $num_sessions = intval($workshop_node->field_number_sessions[LANGUAGE_NONE][0]['value']);
  for ($i = 0; $i < $num_sessions; $i++) {
    $node = new stdClass();
    $node->type = "session";
    node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
    $node->language = $langcode; // Or e.g. 'en' if locale is enabled
    $node->uid = $user->uid;
    $node->status = 1; //(1 or 0): published or not
    $node->promote = 0; //(1 or 0): promoted to front page

    $node->field_workshop[LANGUAGE_NONE][] = array(
        'target_id' => $workshop_node->nid,
        'target_type' => 'node',
    );

    $node->title = "جلسة $workshop_node->title";
    if ($num_sessions > 1) {
      $node->title .= "-" . strval($i + 1);
    }
    $node->field_serial[LANGUAGE_NONE][0]['value'] = strval($i + 1);

    $node = node_submit($node); // Prepare node for saving
    node_save($node);
  }



  drupal_set_message(t('Corresponding session(s) created.'));
}

/*
 * Get the current 2 day period start date based on camp start date and switch hour.
 * @todo Use configuration options
 */

function adef_camps_get_period_date() {
  $cur_date = new DateTime();
  $switch_hour = variable_get('adef_camps_switch_hour', 21);
  $hours_to_switch_hour = 24 - $switch_hour;
  $start_date = variable_get('adef_camps_start_date', array('year' => 2013, 'month' => 8, 'day' => 16));
  $start_date = date_create($start_date['year'] . '-' . $start_date['month'] . '-' . $start_date['day']);
  $start_date->sub(new DateInterval('PT'. $hours_to_switch_hour . 'H'));
  $breakpoints = variable_get('adef_camps_daybreakpoints', '2');
  $breakpoints = explode(',', $breakpoints);
  $end_date = new DateTime;
  if (count($breakpoints) == 1) {
    
  } else {
    for ($i = 1; $i < (count($breakpoints)); $i++) {
      $bp = $breakpoints[$i];
      $start_date->add(new DateInterval('P'. $breakpoints[$i-1] .'D'));
      $end_date->setTimestamp($start_date->getTimeStamp() + (24 * 60 * 60 * $bp));
      if ($cur_date >= $start_date && $cur_date < $end_date) {
        $start_date->add(new DateInterval('PT'. $hours_to_switch_hour . 'H'));
        $start_date = getdate($start_date->getTimeStamp());
        $days_to_show = $breakpoints[$i];
        return array('year' => $start_date['year'], 'month' => $start_date['mon'], 'day' => $start_date['mday'], 'days_to_show' => $days_to_show);
      }
    }
  }
  $start_date = getdate();
  return array(array('year' => $start_date, 'month' => $start_date['month'], 'day' => $start_date['mday'], 'days_to_show' => 1));
  // old code
  $cur_date = getdate();
  $day = $cur_date['mday'];
  $hour = $cur_date['hours'];
  $switch_hour = variable_get('adef_camps_switch_hour', 21);
  $start_date = variable_get('adef_camps_start_date', array('year' => 2013, 'month' => 8, 'day' => 16));
  $start_day = intval($start_date['day']);
  if ($day == $start_day) {
    return $start_date;
  }
  $day_diff = $day - $start_day;
  $period_day = (intval($day_diff / 2) * 2) + $start_day;
  if ($day == $period_day + 1 && $hour >= $switch_hour) {
    $period_day += 2;
  }
  $start_date['day'] = $period_day;
  //manual override for 2014
  if ($start_date['day'] >= 19) {
    $start_date['day'] += 1;
  }
  return $start_date;
}

/**
 * Implements hook_date_formats();
 */
function adef_camps_date_formats() {
  return array(
      array(
          'type' => 'time_only',
          'format' => 'H:i',
          'locales' => array(),
      ),
      array(
          'type' => 'time_only_12h',
          'format' => 'h:i',
          'locales' => array(),
      ),
      array(
          'type' => 'short_date_only',
          'format' => 'j/n/Y',
          'locales' => array(),
      ),
      array(
          'type' => 'date_only',
          'format' => 'l j F',
          'locales' => array(),
      ),
  );
}

/**
 * Implements hook_date_format_types();
 */
function adef_camps_date_format_types() {
  return array(
      'time_only' => t('Time Only'),
      'time_only_12h' => t('Time Only 12h'),
      'short_date_only' => t('Short Date Only'),
      'date_only' => t('Date Only')
  );
}
